spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dao?characterEncoding=UTF-8&serverTimezone=UTC
    username: uxfac
    password: uxfac
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true